### ISSUE TITLE
Problem Formulations

### ISSUE THREAD

**Issue by ZjuYTW** [Jiayuli-CU/Soulight#1]
# TODOs
* Is the problem relevant a year/2-year/5-year from now?
* What is the challenging aspect of the problem? Have others not thought of the problem or is the solution difficult to come up with?
* What is your approach to solving it? What is novel about the solution?
* How will you prevent people from copying your solution?(which you patent it?)

**Comment by Jiayuli-CU** [comment]
### Is the problem relevant a year/2-year/5-year from now?
At present, the mainstream social platforms in the market, such as Facebook and Instagram, have perfect functions. Users can post pictures and pictures or comment on other users' posts, as well as connect with each other through private chats. This brings a problem: users' privacy cannot be effectively guaranteed. Their personal information is likely to be leaked through their homepage, blog posts and pictures. Moreover, due to the existence of followers, they cannot express their true thoughts. Therefore, this project hopes to design a lightweight social networking site, that is, cancel the above functions, and all users can access anonymously. Users socialize with each other by sending messages and receiving messages randomly assigned by the platform. At present, there is no similar social platform in the market, so the problem is relevant at least 5 years from now.

**Comment by ZjuYTW** [comment]
### What is the challenging aspect of the problem? 
* Firstly, to solve the privacy problem, as the App providers, the company should pay more attention to the user's information. That is, the company should show the minimum personal Infos on the post as they can to keep anonymity.
* Secondly, as an application that aims at global marketing, how to deal with cross-language and cross-culture should also be carefully considered. That is, the company should provide a proper classification of different posts.
* Thirdly, technically speaking, we should well-design our front & back end to avoid the high throughput and high concurrency problems in the future.

### Have others not thought of the problem or is the solution difficult to come up with?
As we know,  nowadays mainstreams are all doing their acquaintances socializing apps which means the users are many centralized nodes. In our scenarios, *Soulight* is more like a decentralization social networking app. So we are facing a completely different challenge.

However, as we list the three problems out separately, we hopefully find all these small problems are solvable.  we could address this by referring to what other companies did in the past for every sub-problem!

**Comment by Jiayuli-CU** [comment]
### How will you prevent people from copying your solution?(which you patent it?)
We will prevent people from copying our solution by the following measures:
- Set the business code as close-source, especially the part relevant to backend APIs, so as to hide the implementation logics of each interface in the system.
- Design the system as a micro-service architecture and deployed separately into different remote servers, especially the core algorithm module. In this way, even if one of the servers is attacked, it will not leak the entire system code.
- Mark patent ownership, certificate and other relevant legal information clearly on the homepage of the system website in order to warn potential copycats.
